### ISSUE TITLE
Doesn't work in AT

### ISSUE THREAD

**Issue by simondate** [simondate/adapt-double-accordion#4]

**Comment by moxxuk** [comment]
DOES work in the authoring tool, however the sub items are blank even though I've filled them out in the editor.

**Comment by simondate** [comment]
Sorry, by doesn't work in AT I meant not properly.

I'll try and fix this when I have a chance!

**Comment by moxxuk** [comment]
Oops, didn't realise you were the project owner! I look forward to the fix, looks like a good plugin.

**Comment by simondate** [comment]
Fixed in the last commit
